logging:
    config: classpath:logback.xml
#server:
#    port: 8081
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://123.57.14.133:8093/xxl-job-admin
        executor:
            address: ''
            appname: itheima-stock-executor
            ip: ''
            logpath: ./logs
            logretentiondays: 30
            port: 7979